import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import HeroUpload from '../components/HeroUpload';
import LoadingOverlay from '../components/LoadingOverlay';
import { useStore } from '../store/useStore';
import { injectTemplate } from '../utils/masterTemplate';

function fakeGenerate({ mode, title, description, hero }) {
  const generatedTitle = mode === 'title' && title ? `${title} | Sociallia News` : `Breaking: ${description.slice(0, 50)}`;
  const rawHtml = `<p>${description || 'Local story details generated by Sociallia News Agent.'}</p><p>This is AI-assisted draft content for editorial refinement.</p>`;

  return {
    title: generatedTitle,
    labels: ['news', 'sociallia', 'update'],
    slug: generatedTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
    search_description: `${description}`.slice(0, 150),
    content_html: injectTemplate({ heroImage: hero, contentHtml: rawHtml }),
  };
}

export default function GeneratePage() {
  const navigate = useNavigate();
  const postData = useStore((state) => state.postData);
  const updatePostData = useStore((state) => state.updatePostData);
  const upsertCurrentPost = useStore((state) => state.upsertCurrentPost);
  const [mode, setMode] = useState('title');
  const [seedTitle, setSeedTitle] = useState(postData.title);
  const [description, setDescription] = useState(postData.search_description);
  const [loading, setLoading] = useState(false);

  const onGenerate = () => {
    setLoading(true);
    setTimeout(() => {
      const result = fakeGenerate({
        mode,
        title: seedTitle,
        description,
        hero: postData.hero_image,
      });

      updatePostData(result);
      upsertCurrentPost('draft');
      setLoading(false);
      navigate('/editor');
    }, 1400);
  };

  return (
    <div className="page generate-page">
      {loading ? <LoadingOverlay /> : null}
      <h1>Sociallia News Agent</h1>
      <section className="card">
        <h2>1) Input Mode</h2>
        <div className="row">
          <label><input type="radio" checked={mode === 'title'} onChange={() => setMode('title')} /> Title + Description</label>
          <label><input type="radio" checked={mode === 'description'} onChange={() => setMode('description')} /> Only Description</label>
        </div>

        {mode === 'title' ? (
          <input placeholder="Seed title" value={seedTitle} onChange={(event) => setSeedTitle(event.target.value)} />
        ) : null}

        <textarea
          rows={6}
          placeholder="Story facts, angle, location, and context"
          value={description}
          onChange={(event) => setDescription(event.target.value)}
        />

        <h2>2) Hero Image Upload</h2>
        <HeroUpload />
      </section>

      <button type="button" className="btn generate" onClick={onGenerate}>Generate</button>
    </div>
  );
}
